# Generated by Django 6.0 on 2026-02-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_county', models.CharField(blank=True, choices=[('001', 'Adams'), ('002', 'Alexander'), ('003', 'Bond'), ('004', 'Boone'), ('005', 'Brown'), ('006', 'Bureau'), ('007', 'Calhoun'), ('008', 'Carroll'), ('009', 'Cass'), ('010', 'Champaign'), ('011', 'Christian'), ('012', 'Clark'), ('013', 'Clay'), ('014', 'Clinton'), ('015', 'Coles'), ('016', 'Cook'), ('017', 'Crawford'), ('018', 'Cumberland'), ('019', 'Dekalb'), ('020', 'Dewitt'), ('021', 'Douglas'), ('022', 'Dupage'), ('023', 'Edgar'), ('024', 'Edwards'), ('025', 'Effingham'), ('026', 'Fayette'), ('027', 'Ford'), ('028', 'Franklin'), ('029', 'Fulton'), ('030', 'Gallatin'), ('031', 'Greene'), ('032', 'Grundy'), ('033', 'Hamilton'), ('034', 'Hancock'), ('035', 'Hardin'), ('036', 'Henderson'), ('037', 'Henry'), ('038', 'Iroquois'), ('039', 'Jackson'), ('040', 'Jasper'), ('041', 'Jefferson'), ('042', 'Jersey'), ('043', 'Jo Daviess'), ('044', 'Johnson'), ('045', 'Kane'), ('046', 'Kankakee'), ('047', 'Kendall'), ('048', 'Knox'), ('049', 'Lake'), ('050', 'La Salle'), ('051', 'Lawrence'), ('052', 'Lee'), ('053', 'Livingston'), ('054', 'Logan'), ('055', 'Macon'), ('056', 'Macoupin'), ('057', 'Madison'), ('058', 'Marion'), ('059', 'Marshall'), ('060', 'Mason'), ('061', 'Massac'), ('062', 'McDonough'), ('063', 'McHenry'), ('064', 'McLean'), ('065', 'Menard'), ('066', 'Mercer'), ('067', 'Monroe'), ('068', 'Montgomery'), ('069', 'Morgan'), ('070', 'Moultrie'), ('071', 'Ogle'), ('072', 'Peoria'), ('073', 'Perry'), ('074', 'Piatt'), ('075', 'Pike'), ('076', 'Pope'), ('077', 'Pulaski'), ('078', 'Putnam'), ('079', 'Randolph'), ('080', 'Richland'), ('081', 'Rock Island'), ('082', 'Saint Clair'), ('083', 'Saline'), ('084', 'Sangamon'), ('085', 'Schuyler'), ('086', 'Scott'), ('087', 'Shelby'), ('088', 'Stark'), ('089', 'Stephenson'), ('090', 'Tazewell'), ('091', 'Union'), ('092', 'Vermilion'), ('093', 'Wabash'), ('094', 'Warren'), ('095', 'Washington'), ('096', 'Wayne'), ('097', 'White'), ('098', 'Whiteside'), ('099', 'Will'), ('100', 'Williamson'), ('101', 'Winnebago'), ('102', 'Woodford')], max_length=3, null=True)),
                ('birth_record_image', models.ImageField(blank=True, null=True, upload_to='birth_records/')),
            ],
            options={
                'verbose_name': 'Birth',
                'verbose_name_plural': 'Births',
                'ordering': ['birth_date', 'birth_county'],
            },
        ),
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_county', models.CharField(blank=True, choices=[('001', 'Adams'), ('002', 'Alexander'), ('003', 'Bond'), ('004', 'Boone'), ('005', 'Brown'), ('006', 'Bureau'), ('007', 'Calhoun'), ('008', 'Carroll'), ('009', 'Cass'), ('010', 'Champaign'), ('011', 'Christian'), ('012', 'Clark'), ('013', 'Clay'), ('014', 'Clinton'), ('015', 'Coles'), ('016', 'Cook'), ('017', 'Crawford'), ('018', 'Cumberland'), ('019', 'Dekalb'), ('020', 'Dewitt'), ('021', 'Douglas'), ('022', 'Dupage'), ('023', 'Edgar'), ('024', 'Edwards'), ('025', 'Effingham'), ('026', 'Fayette'), ('027', 'Ford'), ('028', 'Franklin'), ('029', 'Fulton'), ('030', 'Gallatin'), ('031', 'Greene'), ('032', 'Grundy'), ('033', 'Hamilton'), ('034', 'Hancock'), ('035', 'Hardin'), ('036', 'Henderson'), ('037', 'Henry'), ('038', 'Iroquois'), ('039', 'Jackson'), ('040', 'Jasper'), ('041', 'Jefferson'), ('042', 'Jersey'), ('043', 'Jo Daviess'), ('044', 'Johnson'), ('045', 'Kane'), ('046', 'Kankakee'), ('047', 'Kendall'), ('048', 'Knox'), ('049', 'Lake'), ('050', 'La Salle'), ('051', 'Lawrence'), ('052', 'Lee'), ('053', 'Livingston'), ('054', 'Logan'), ('055', 'Macon'), ('056', 'Macoupin'), ('057', 'Madison'), ('058', 'Marion'), ('059', 'Marshall'), ('060', 'Mason'), ('061', 'Massac'), ('062', 'McDonough'), ('063', 'McHenry'), ('064', 'McLean'), ('065', 'Menard'), ('066', 'Mercer'), ('067', 'Monroe'), ('068', 'Montgomery'), ('069', 'Morgan'), ('070', 'Moultrie'), ('071', 'Ogle'), ('072', 'Peoria'), ('073', 'Perry'), ('074', 'Piatt'), ('075', 'Pike'), ('076', 'Pope'), ('077', 'Pulaski'), ('078', 'Putnam'), ('079', 'Randolph'), ('080', 'Richland'), ('081', 'Rock Island'), ('082', 'Saint Clair'), ('083', 'Saline'), ('084', 'Sangamon'), ('085', 'Schuyler'), ('086', 'Scott'), ('087', 'Shelby'), ('088', 'Stark'), ('089', 'Stephenson'), ('090', 'Tazewell'), ('091', 'Union'), ('092', 'Vermilion'), ('093', 'Wabash'), ('094', 'Warren'), ('095', 'Washington'), ('096', 'Wayne'), ('097', 'White'), ('098', 'Whiteside'), ('099', 'Will'), ('100', 'Williamson'), ('101', 'Winnebago'), ('102', 'Woodford')], max_length=3, null=True)),
                ('death_record_image', models.ImageField(blank=True, null=True, upload_to='death_records/')),
            ],
            options={
                'verbose_name': 'Death',
                'verbose_name_plural': 'Deaths',
                'ordering': ['death_date', 'death_county'],
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name', 'middle_name', 'sex'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_county',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_county',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='marriage_date',
        ),
        migrations.AddField(
            model_name='marriage',
            name='death_record_image',
            field=models.ImageField(blank=True, null=True, upload_to='marriage_records/'),
        ),
    ]
